import { Category } from '../types';

export const area: Category = {
    id: 'area',
    name: 'Area',
    icon: '📐',
    description: 'Convert between area units such as square meters, acres, hectares, square feet and more.',
    baseUnit: 'square-meter',
    units: [
        { id: 'square-meter', name: 'Square Meter', symbol: 'm²', factor: 1 },
        { id: 'square-kilometer', name: 'Square Kilometer', symbol: 'km²', factor: 1e6 },
        { id: 'square-centimeter', name: 'Square Centimeter', symbol: 'cm²', factor: 1e-4 },
        { id: 'square-millimeter', name: 'Square Millimeter', symbol: 'mm²', factor: 1e-6 },
        { id: 'hectare', name: 'Hectare', symbol: 'ha', factor: 10000 },
        { id: 'acre', name: 'Acre', symbol: 'ac', factor: 4046.8564224 },
        { id: 'square-mile', name: 'Square Mile', symbol: 'mi²', factor: 2589988.110336 },
        { id: 'square-yard', name: 'Square Yard', symbol: 'yd²', factor: 0.83612736 },
        { id: 'square-foot', name: 'Square Foot', symbol: 'ft²', factor: 0.09290304 },
        { id: 'square-inch', name: 'Square Inch', symbol: 'in²', factor: 6.4516e-4 },
        { id: 'are', name: 'Are', symbol: 'a', factor: 100 },
        { id: 'decare', name: 'Decare', symbol: 'daa', factor: 1000 },
        { id: 'square-rod', name: 'Square Rod', symbol: 'rd²', factor: 25.29285264 },
        { id: 'rood', name: 'Rood', symbol: 'rood', factor: 1011.7141056 },
        { id: 'barn', name: 'Barn', symbol: 'b', factor: 1e-28 },
        { id: 'square-nautical-mile', name: 'Square Nautical Mile', symbol: 'nmi²', factor: 3429904 },
        { id: 'dunam', name: 'Dunam', symbol: 'dunam', factor: 1000 },
        { id: 'tsubo', name: 'Tsubo', symbol: 'tsubo', factor: 3.306 },
        { id: 'pyeong', name: 'Pyeong', symbol: 'pyeong', factor: 3.3058 },
        { id: 'rai', name: 'Rai (Thai)', symbol: 'rai', factor: 1600 },
        { id: 'square-chain', name: 'Square Chain', symbol: 'ch²', factor: 404.68564224 },
        { id: 'square-decimeter', name: 'Square Decimeter', symbol: 'dm²', factor: 0.01 },
        { id: 'square-hectometer', name: 'Square Hectometer', symbol: 'hm²', factor: 10000 },
        { id: 'section', name: 'Section', symbol: 'section', factor: 2589988.110336 },
        { id: 'township', name: 'Township', symbol: 'twp', factor: 93239571.972 },
        { id: 'circular-mil', name: 'Circular Mil', symbol: 'cmil', factor: 5.067e-10 },
    ],
};
