import { Category } from '../types';

export const cooking: Category = {
    id: 'cooking',
    name: 'Cooking Units',
    icon: '🍳',
    description: 'Convert between cooking measurement units such as cups, tablespoons, teaspoons, milliliters and more.',
    baseUnit: 'milliliter-cooking',
    units: [
        { id: 'milliliter-cooking', name: 'Milliliter', symbol: 'mL', factor: 1 },
        { id: 'liter-cooking', name: 'Liter', symbol: 'L', factor: 1000 },
        { id: 'teaspoon', name: 'Teaspoon (US)', symbol: 'tsp', factor: 4.92892 },
        { id: 'tablespoon', name: 'Tablespoon (US)', symbol: 'tbsp', factor: 14.7868 },
        { id: 'fluid-ounce', name: 'Fluid Ounce (US)', symbol: 'fl oz', factor: 29.5735 },
        { id: 'cup', name: 'Cup (US)', symbol: 'cup', factor: 236.588 },
        { id: 'pint-cooking', name: 'Pint (US)', symbol: 'pt', factor: 473.176 },
        { id: 'quart-cooking', name: 'Quart (US)', symbol: 'qt', factor: 946.353 },
        { id: 'gallon-cooking', name: 'Gallon (US)', symbol: 'gal', factor: 3785.41 },
        { id: 'teaspoon-metric', name: 'Teaspoon (metric)', symbol: 'tsp', factor: 5 },
        { id: 'tablespoon-metric', name: 'Tablespoon (metric)', symbol: 'tbsp', factor: 15 },
        { id: 'tablespoon-au', name: 'Tablespoon (Australian)', symbol: 'tbsp AU', factor: 20 },
        { id: 'cup-metric', name: 'Cup (metric)', symbol: 'cup', factor: 250 },
        { id: 'cup-uk', name: 'Cup (UK)', symbol: 'cup UK', factor: 284.131 },
        { id: 'cup-japanese', name: 'Cup (Japanese)', symbol: '合', factor: 200 },
        { id: 'dessertspoon', name: 'Dessertspoon', symbol: 'dsp', factor: 10 },
        { id: 'drop-cooking', name: 'Drop', symbol: 'drop', factor: 0.05 },
        { id: 'pinch', name: 'Pinch', symbol: 'pinch', factor: 0.31 },
        { id: 'dash', name: 'Dash', symbol: 'dash', factor: 0.62 },
        { id: 'smidgen', name: 'Smidgen', symbol: 'smidgen', factor: 0.155 },
        { id: 'gill-cooking', name: 'Gill', symbol: 'gill', factor: 118.294 },
        { id: 'jigger', name: 'Jigger', symbol: 'jigger', factor: 44.3603 },
        { id: 'deciliter-cooking', name: 'Deciliter', symbol: 'dL', factor: 100 },
        { id: 'centiliter-cooking', name: 'Centiliter', symbol: 'cL', factor: 10 },
    ],
};
