import { Category } from '../types';

// Static exchange rates (vs USD) — for demonstration only
export const currency: Category = {
    id: 'currency',
    name: 'Currency',
    icon: '💱',
    description: 'Convert between currencies using static exchange rates. Note: rates are approximate and for reference only.',
    baseUnit: 'usd',
    units: [
        { id: 'usd', name: 'US Dollar', symbol: 'USD', factor: 1 },
        { id: 'eur', name: 'Euro', symbol: 'EUR', factor: 0.92 },
        { id: 'gbp', name: 'British Pound', symbol: 'GBP', factor: 0.79 },
        { id: 'jpy', name: 'Japanese Yen', symbol: 'JPY', factor: 149.5 },
        { id: 'cny', name: 'Chinese Yuan', symbol: 'CNY', factor: 7.24 },
        { id: 'thb', name: 'Thai Baht', symbol: 'THB', factor: 35.5 },
        { id: 'inr', name: 'Indian Rupee', symbol: 'INR', factor: 83.1 },
        { id: 'krw', name: 'South Korean Won', symbol: 'KRW', factor: 1330 },
        { id: 'sgd', name: 'Singapore Dollar', symbol: 'SGD', factor: 1.35 },
        { id: 'aud', name: 'Australian Dollar', symbol: 'AUD', factor: 1.53 },
        { id: 'cad', name: 'Canadian Dollar', symbol: 'CAD', factor: 1.36 },
        { id: 'chf', name: 'Swiss Franc', symbol: 'CHF', factor: 0.88 },
        { id: 'hkd', name: 'Hong Kong Dollar', symbol: 'HKD', factor: 7.83 },
        { id: 'nzd', name: 'New Zealand Dollar', symbol: 'NZD', factor: 1.63 },
        { id: 'sek', name: 'Swedish Krona', symbol: 'SEK', factor: 10.5 },
        { id: 'nok', name: 'Norwegian Krone', symbol: 'NOK', factor: 10.6 },
        { id: 'mxn', name: 'Mexican Peso', symbol: 'MXN', factor: 17.1 },
        { id: 'brl', name: 'Brazilian Real', symbol: 'BRL', factor: 4.97 },
        { id: 'zar', name: 'South African Rand', symbol: 'ZAR', factor: 18.6 },
        { id: 'rub', name: 'Russian Ruble', symbol: 'RUB', factor: 90.5 },
        { id: 'try', name: 'Turkish Lira', symbol: 'TRY', factor: 28.9 },
        { id: 'aed', name: 'UAE Dirham', symbol: 'AED', factor: 3.67 },
        { id: 'sar', name: 'Saudi Riyal', symbol: 'SAR', factor: 3.75 },
        { id: 'php', name: 'Philippine Peso', symbol: 'PHP', factor: 56.2 },
        { id: 'myr', name: 'Malaysian Ringgit', symbol: 'MYR', factor: 4.72 },
        { id: 'idr', name: 'Indonesian Rupiah', symbol: 'IDR', factor: 15600 },
        { id: 'vnd', name: 'Vietnamese Dong', symbol: 'VND', factor: 24500 },
        { id: 'twd', name: 'Taiwan Dollar', symbol: 'TWD', factor: 31.5 },
        { id: 'pln', name: 'Polish Zloty', symbol: 'PLN', factor: 4.05 },
        { id: 'dkk', name: 'Danish Krone', symbol: 'DKK', factor: 6.87 },
        { id: 'egp', name: 'Egyptian Pound', symbol: 'EGP', factor: 30.9 },
        { id: 'btc', name: 'Bitcoin', symbol: 'BTC', factor: 0.000024 },
        { id: 'eth', name: 'Ethereum', symbol: 'ETH', factor: 0.00043 },
    ],
};
