import { Category } from '../types';

export const dataSize: Category = {
    id: 'data-size',
    name: 'Data Size',
    icon: '💾',
    description: 'Convert between data size units such as bytes, kilobytes, megabytes, gigabytes, terabytes and more.',
    baseUnit: 'byte',
    units: [
        { id: 'bit', name: 'Bit', symbol: 'b', factor: 0.125 },
        { id: 'nibble', name: 'Nibble', symbol: 'nibble', factor: 0.5 },
        { id: 'byte', name: 'Byte', symbol: 'B', factor: 1 },
        { id: 'kilobyte', name: 'Kilobyte', symbol: 'KB', factor: 1000 },
        { id: 'megabyte', name: 'Megabyte', symbol: 'MB', factor: 1e6 },
        { id: 'gigabyte', name: 'Gigabyte', symbol: 'GB', factor: 1e9 },
        { id: 'terabyte', name: 'Terabyte', symbol: 'TB', factor: 1e12 },
        { id: 'petabyte', name: 'Petabyte', symbol: 'PB', factor: 1e15 },
        { id: 'exabyte', name: 'Exabyte', symbol: 'EB', factor: 1e18 },
        { id: 'zettabyte', name: 'Zettabyte', symbol: 'ZB', factor: 1e21 },
        { id: 'yottabyte', name: 'Yottabyte', symbol: 'YB', factor: 1e24 },
        { id: 'kibibyte', name: 'Kibibyte', symbol: 'KiB', factor: 1024 },
        { id: 'mebibyte', name: 'Mebibyte', symbol: 'MiB', factor: 1048576 },
        { id: 'gibibyte', name: 'Gibibyte', symbol: 'GiB', factor: 1073741824 },
        { id: 'tebibyte', name: 'Tebibyte', symbol: 'TiB', factor: 1099511627776 },
        { id: 'pebibyte', name: 'Pebibyte', symbol: 'PiB', factor: 1125899906842624 },
        { id: 'exbibyte', name: 'Exbibyte', symbol: 'EiB', factor: 1.1529e18 },
        { id: 'kilobit', name: 'Kilobit', symbol: 'kb', factor: 125 },
        { id: 'megabit', name: 'Megabit', symbol: 'Mb', factor: 125000 },
        { id: 'gigabit', name: 'Gigabit', symbol: 'Gb', factor: 1.25e8 },
        { id: 'terabit', name: 'Terabit', symbol: 'Tb', factor: 1.25e11 },
        { id: 'word', name: 'Word (16-bit)', symbol: 'word', factor: 2 },
        { id: 'dword', name: 'Double Word (32-bit)', symbol: 'dword', factor: 4 },
        { id: 'qword', name: 'Quad Word (64-bit)', symbol: 'qword', factor: 8 },
        { id: 'block', name: 'Block (512 bytes)', symbol: 'block', factor: 512 },
        { id: 'cluster', name: 'Cluster (4 KiB)', symbol: 'cluster', factor: 4096 },
        { id: 'floppy-disk', name: 'Floppy Disk (1.44 MB)', symbol: 'floppy', factor: 1474560 },
        { id: 'cd', name: 'CD (700 MB)', symbol: 'CD', factor: 7e8 },
        { id: 'dvd', name: 'DVD (4.7 GB)', symbol: 'DVD', factor: 4.7e9 },
        { id: 'blu-ray', name: 'Blu-ray (25 GB)', symbol: 'BD', factor: 2.5e10 },
    ],
};
