import { Category } from '../types';

export const energy: Category = {
    id: 'energy',
    name: 'Energy',
    icon: '⚡',
    description: 'Convert between energy units such as Joule, calorie, BTU, kilowatt-hour, electronvolt and more.',
    baseUnit: 'joule',
    units: [
        { id: 'joule', name: 'Joule', symbol: 'J', factor: 1 },
        { id: 'kilojoule', name: 'Kilojoule', symbol: 'kJ', factor: 1000 },
        { id: 'megajoule', name: 'Megajoule', symbol: 'MJ', factor: 1e6 },
        { id: 'gigajoule', name: 'Gigajoule', symbol: 'GJ', factor: 1e9 },
        { id: 'calorie', name: 'Calorie', symbol: 'cal', factor: 4.184 },
        { id: 'kilocalorie', name: 'Kilocalorie', symbol: 'kcal', factor: 4184 },
        { id: 'watt-hour', name: 'Watt Hour', symbol: 'Wh', factor: 3600 },
        { id: 'kilowatt-hour', name: 'Kilowatt Hour', symbol: 'kWh', factor: 3.6e6 },
        { id: 'megawatt-hour', name: 'Megawatt Hour', symbol: 'MWh', factor: 3.6e9 },
        { id: 'btu', name: 'British Thermal Unit', symbol: 'BTU', factor: 1055.06 },
        { id: 'therm', name: 'Therm', symbol: 'thm', factor: 1.055e8 },
        { id: 'foot-pound', name: 'Foot-Pound', symbol: 'ft·lbf', factor: 1.355818 },
        { id: 'electronvolt', name: 'Electronvolt', symbol: 'eV', factor: 1.602e-19 },
        { id: 'kilo-electronvolt', name: 'Kiloelectronvolt', symbol: 'keV', factor: 1.602e-16 },
        { id: 'mega-electronvolt', name: 'Megaelectronvolt', symbol: 'MeV', factor: 1.602e-13 },
        { id: 'erg', name: 'Erg', symbol: 'erg', factor: 1e-7 },
        { id: 'hartree', name: 'Hartree', symbol: 'Eₕ', factor: 4.3597e-18 },
        { id: 'rydberg', name: 'Rydberg', symbol: 'Ry', factor: 2.1799e-18 },
        { id: 'ton-of-tnt', name: 'Ton of TNT', symbol: 'tTNT', factor: 4.184e9 },
        { id: 'barrel-of-oil-equiv', name: 'Barrel of Oil Equivalent', symbol: 'BOE', factor: 6.12e9 },
        { id: 'ton-of-coal-equiv', name: 'Ton of Coal Equivalent', symbol: 'TCE', factor: 2.93e10 },
        { id: 'millijoule', name: 'Millijoule', symbol: 'mJ', factor: 0.001 },
        { id: 'microjoule', name: 'Microjoule', symbol: 'μJ', factor: 1e-6 },
        { id: 'nanojoule', name: 'Nanojoule', symbol: 'nJ', factor: 1e-9 },
    ],
};
