import { Category } from '../types';

export const length: Category = {
    id: 'length',
    name: 'Length',
    icon: '📏',
    description: 'Convert between length and distance units including meters, feet, inches, kilometers, miles and more.',
    baseUnit: 'meter',
    units: [
        { id: 'meter', name: 'Meter', symbol: 'm', factor: 1 },
        { id: 'kilometer', name: 'Kilometer', symbol: 'km', factor: 1000 },
        { id: 'centimeter', name: 'Centimeter', symbol: 'cm', factor: 0.01 },
        { id: 'millimeter', name: 'Millimeter', symbol: 'mm', factor: 0.001 },
        { id: 'micrometer', name: 'Micrometer', symbol: 'μm', factor: 1e-6 },
        { id: 'nanometer', name: 'Nanometer', symbol: 'nm', factor: 1e-9 },
        { id: 'picometer', name: 'Picometer', symbol: 'pm', factor: 1e-12 },
        { id: 'mile', name: 'Mile', symbol: 'mi', factor: 1609.344 },
        { id: 'yard', name: 'Yard', symbol: 'yd', factor: 0.9144 },
        { id: 'foot', name: 'Foot', symbol: 'ft', factor: 0.3048 },
        { id: 'inch', name: 'Inch', symbol: 'in', factor: 0.0254 },
        { id: 'nautical-mile', name: 'Nautical Mile', symbol: 'nmi', factor: 1852 },
        { id: 'fathom', name: 'Fathom', symbol: 'ftm', factor: 1.8288 },
        { id: 'furlong', name: 'Furlong', symbol: 'fur', factor: 201.168 },
        { id: 'chain', name: 'Chain', symbol: 'ch', factor: 20.1168 },
        { id: 'rod', name: 'Rod', symbol: 'rd', factor: 5.0292 },
        { id: 'league', name: 'League', symbol: 'lea', factor: 4828.032 },
        { id: 'light-year', name: 'Light Year', symbol: 'ly', factor: 9.461e15 },
        { id: 'astronomical-unit', name: 'Astronomical Unit', symbol: 'AU', factor: 1.496e11 },
        { id: 'parsec', name: 'Parsec', symbol: 'pc', factor: 3.086e16 },
        { id: 'angstrom', name: 'Ångström', symbol: 'Å', factor: 1e-10 },
        { id: 'decimeter', name: 'Decimeter', symbol: 'dm', factor: 0.1 },
        { id: 'decameter', name: 'Decameter', symbol: 'dam', factor: 10 },
        { id: 'hectometer', name: 'Hectometer', symbol: 'hm', factor: 100 },
        { id: 'megameter', name: 'Megameter', symbol: 'Mm', factor: 1e6 },
        { id: 'gigameter', name: 'Gigameter', symbol: 'Gm', factor: 1e9 },
        { id: 'thou', name: 'Thou (mil)', symbol: 'thou', factor: 2.54e-5 },
        { id: 'cable', name: 'Cable', symbol: 'cable', factor: 185.2 },
        { id: 'hand', name: 'Hand', symbol: 'hh', factor: 0.1016 },
        { id: 'cubit', name: 'Cubit', symbol: 'cubit', factor: 0.4572 },
        { id: 'span', name: 'Span', symbol: 'span', factor: 0.2286 },
        { id: 'smoot', name: 'Smoot', symbol: 'smoot', factor: 1.7018 },
        { id: 'fermi', name: 'Fermi', symbol: 'fm', factor: 1e-15 },
        { id: 'bohr-radius', name: 'Bohr Radius', symbol: 'a₀', factor: 5.2918e-11 },
        { id: 'earth-radius', name: 'Earth Radius', symbol: 'R⊕', factor: 6.371e6 },
        { id: 'solar-radius', name: 'Solar Radius', symbol: 'R☉', factor: 6.957e8 },
        { id: 'lunar-distance', name: 'Lunar Distance', symbol: 'LD', factor: 3.844e8 },
        { id: 'marathon', name: 'Marathon', symbol: 'marathon', factor: 42195 },
        { id: 'football-field', name: 'Football Field', symbol: 'ff', factor: 91.44 },
    ],
};
