import { Category } from '../types';

export const time: Category = {
    id: 'time',
    name: 'Time',
    icon: '⏰',
    description: 'Convert between time units such as seconds, minutes, hours, days, weeks, months, years and more.',
    baseUnit: 'second',
    units: [
        { id: 'second', name: 'Second', symbol: 's', factor: 1 },
        { id: 'millisecond', name: 'Millisecond', symbol: 'ms', factor: 0.001 },
        { id: 'microsecond', name: 'Microsecond', symbol: 'μs', factor: 1e-6 },
        { id: 'nanosecond', name: 'Nanosecond', symbol: 'ns', factor: 1e-9 },
        { id: 'picosecond', name: 'Picosecond', symbol: 'ps', factor: 1e-12 },
        { id: 'minute', name: 'Minute', symbol: 'min', factor: 60 },
        { id: 'hour', name: 'Hour', symbol: 'h', factor: 3600 },
        { id: 'day', name: 'Day', symbol: 'd', factor: 86400 },
        { id: 'week', name: 'Week', symbol: 'wk', factor: 604800 },
        { id: 'fortnight', name: 'Fortnight', symbol: 'fn', factor: 1209600 },
        { id: 'month', name: 'Month (30 days)', symbol: 'mo', factor: 2592000 },
        { id: 'quarter', name: 'Quarter (91.25 days)', symbol: 'qtr', factor: 7884000 },
        { id: 'year', name: 'Year (365.25 days)', symbol: 'yr', factor: 31557600 },
        { id: 'decade', name: 'Decade', symbol: 'dec', factor: 315576000 },
        { id: 'century', name: 'Century', symbol: 'c', factor: 3155760000 },
        { id: 'millennium', name: 'Millennium', symbol: 'ky', factor: 31557600000 },
        { id: 'planck-time', name: 'Planck Time', symbol: 'tₚ', factor: 5.391e-44 },
        { id: 'sidereal-day', name: 'Sidereal Day', symbol: 'sid. d', factor: 86164.1 },
        { id: 'sidereal-year', name: 'Sidereal Year', symbol: 'sid. yr', factor: 31558150 },
        { id: 'tropical-year', name: 'Tropical Year', symbol: 'trop. yr', factor: 31556925 },
        { id: 'jiffy', name: 'Jiffy (electronics)', symbol: 'jiffy', factor: 0.01 },
        { id: 'shake', name: 'Shake', symbol: 'shake', factor: 1e-8 },
        { id: 'svedberg', name: 'Svedberg', symbol: 'S', factor: 1e-13 },
        { id: 'dog-year', name: 'Dog Year', symbol: 'dog yr', factor: 31557600 / 7 },
    ],
};
