import { Category } from '../types';

export const volume: Category = {
    id: 'volume',
    name: 'Volume',
    icon: '🧊',
    description: 'Convert between volume units such as liters, gallons, cubic meters, cups, tablespoons and more.',
    baseUnit: 'liter',
    units: [
        { id: 'liter', name: 'Liter', symbol: 'L', factor: 1 },
        { id: 'milliliter', name: 'Milliliter', symbol: 'mL', factor: 0.001 },
        { id: 'cubic-meter', name: 'Cubic Meter', symbol: 'm³', factor: 1000 },
        { id: 'cubic-centimeter', name: 'Cubic Centimeter', symbol: 'cm³', factor: 0.001 },
        { id: 'cubic-millimeter', name: 'Cubic Millimeter', symbol: 'mm³', factor: 1e-6 },
        { id: 'cubic-kilometer', name: 'Cubic Kilometer', symbol: 'km³', factor: 1e12 },
        { id: 'cubic-inch', name: 'Cubic Inch', symbol: 'in³', factor: 0.016387064 },
        { id: 'cubic-foot', name: 'Cubic Foot', symbol: 'ft³', factor: 28.316846592 },
        { id: 'cubic-yard', name: 'Cubic Yard', symbol: 'yd³', factor: 764.554857984 },
        { id: 'gallon-us', name: 'US Gallon', symbol: 'gal', factor: 3.785411784 },
        { id: 'gallon-uk', name: 'Imperial Gallon', symbol: 'imp gal', factor: 4.54609 },
        { id: 'quart-us', name: 'US Quart', symbol: 'qt', factor: 0.946352946 },
        { id: 'pint-us', name: 'US Pint', symbol: 'pt', factor: 0.473176473 },
        { id: 'cup-us', name: 'US Cup', symbol: 'cup', factor: 0.2365882365 },
        { id: 'fluid-ounce-us', name: 'US Fluid Ounce', symbol: 'fl oz', factor: 0.0295735296 },
        { id: 'tablespoon-us', name: 'US Tablespoon', symbol: 'tbsp', factor: 0.0147867648 },
        { id: 'teaspoon-us', name: 'US Teaspoon', symbol: 'tsp', factor: 0.0049289216 },
        { id: 'pint-uk', name: 'Imperial Pint', symbol: 'imp pt', factor: 0.56826125 },
        { id: 'quart-uk', name: 'Imperial Quart', symbol: 'imp qt', factor: 1.1365225 },
        { id: 'fluid-ounce-uk', name: 'Imperial Fluid Ounce', symbol: 'imp fl oz', factor: 0.0284130625 },
        { id: 'deciliter', name: 'Deciliter', symbol: 'dL', factor: 0.1 },
        { id: 'centiliter', name: 'Centiliter', symbol: 'cL', factor: 0.01 },
        { id: 'hectoliter', name: 'Hectoliter', symbol: 'hL', factor: 100 },
        { id: 'kiloliter', name: 'Kiloliter', symbol: 'kL', factor: 1000 },
        { id: 'megaliter', name: 'Megaliter', symbol: 'ML', factor: 1e6 },
        { id: 'microliter', name: 'Microliter', symbol: 'μL', factor: 1e-6 },
        { id: 'barrel-oil', name: 'Barrel (Oil)', symbol: 'bbl', factor: 158.987295 },
        { id: 'barrel-us', name: 'Barrel (US)', symbol: 'US bbl', factor: 119.240471 },
        { id: 'barrel-uk', name: 'Barrel (UK)', symbol: 'imp bbl', factor: 163.65924 },
        { id: 'gill-us', name: 'US Gill', symbol: 'gi', factor: 0.118294118 },
        { id: 'gill-uk', name: 'Imperial Gill', symbol: 'imp gi', factor: 0.142065312 },
        { id: 'drop', name: 'Drop', symbol: 'drop', factor: 5e-5 },
        { id: 'bushel-us', name: 'US Bushel', symbol: 'bu', factor: 35.23907 },
        { id: 'peck-us', name: 'US Peck', symbol: 'pk', factor: 8.809768 },
        { id: 'cord', name: 'Cord', symbol: 'cord', factor: 3624.556 },
        { id: 'hogshead', name: 'Hogshead', symbol: 'hhd', factor: 238.481 },
    ],
};
