import { Category } from '../types';

export const weight: Category = {
    id: 'weight',
    name: 'Weight / Mass',
    icon: '⚖️',
    description: 'Convert between weight and mass units such as kilograms, pounds, ounces, grams, tons and more.',
    baseUnit: 'kilogram',
    units: [
        { id: 'kilogram', name: 'Kilogram', symbol: 'kg', factor: 1 },
        { id: 'gram', name: 'Gram', symbol: 'g', factor: 0.001 },
        { id: 'milligram', name: 'Milligram', symbol: 'mg', factor: 1e-6 },
        { id: 'microgram', name: 'Microgram', symbol: 'μg', factor: 1e-9 },
        { id: 'nanogram', name: 'Nanogram', symbol: 'ng', factor: 1e-12 },
        { id: 'metric-ton', name: 'Metric Ton', symbol: 't', factor: 1000 },
        { id: 'pound', name: 'Pound', symbol: 'lb', factor: 0.45359237 },
        { id: 'ounce', name: 'Ounce', symbol: 'oz', factor: 0.028349523 },
        { id: 'stone', name: 'Stone', symbol: 'st', factor: 6.35029318 },
        { id: 'short-ton', name: 'Short Ton (US)', symbol: 'ton', factor: 907.18474 },
        { id: 'long-ton', name: 'Long Ton (UK)', symbol: 'long ton', factor: 1016.0469 },
        { id: 'carat', name: 'Carat', symbol: 'ct', factor: 0.0002 },
        { id: 'grain', name: 'Grain', symbol: 'gr', factor: 6.479891e-5 },
        { id: 'dram', name: 'Dram', symbol: 'dr', factor: 0.001771845 },
        { id: 'hundredweight-us', name: 'Hundredweight (US)', symbol: 'cwt', factor: 45.359237 },
        { id: 'hundredweight-uk', name: 'Hundredweight (UK)', symbol: 'cwt', factor: 50.802345 },
        { id: 'troy-ounce', name: 'Troy Ounce', symbol: 'oz t', factor: 0.031103477 },
        { id: 'troy-pound', name: 'Troy Pound', symbol: 'lb t', factor: 0.373241721 },
        { id: 'pennyweight', name: 'Pennyweight', symbol: 'dwt', factor: 0.001555174 },
        { id: 'dalton', name: 'Dalton (AMU)', symbol: 'Da', factor: 1.66054e-27 },
        { id: 'slug', name: 'Slug', symbol: 'slug', factor: 14.593903 },
        { id: 'quintal', name: 'Quintal', symbol: 'q', factor: 100 },
        { id: 'decigram', name: 'Decigram', symbol: 'dg', factor: 0.0001 },
        { id: 'centigram', name: 'Centigram', symbol: 'cg', factor: 0.00001 },
        { id: 'hectogram', name: 'Hectogram', symbol: 'hg', factor: 0.1 },
        { id: 'decagram', name: 'Decagram', symbol: 'dag', factor: 0.01 },
        { id: 'earth-mass', name: 'Earth Mass', symbol: 'M⊕', factor: 5.972e24 },
        { id: 'solar-mass', name: 'Solar Mass', symbol: 'M☉', factor: 1.989e30 },
        { id: 'electron-mass', name: 'Electron Mass', symbol: 'mₑ', factor: 9.109e-31 },
        { id: 'tola', name: 'Tola', symbol: 'tola', factor: 0.01166 },
        { id: 'baht', name: 'Baht (Thai)', symbol: 'baht', factor: 0.01522 },
        { id: 'catty', name: 'Catty', symbol: 'catty', factor: 0.6048 },
        { id: 'tael', name: 'Tael', symbol: 'tael', factor: 0.03779 },
    ],
};
